spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: company

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog

logging:
  level:
    ROOT: ERROR