DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT PRIMARY KEY,
TITLE VARCHAR(255) NOT NULL,
AUTHOR_ID BIGINT,
JENRE_ID BIGINT);

DROP TABLE IF EXISTS JENRE;
CREATE TABLE JENRE(ID BIGINT PRIMARY KEY, NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY, NAME VARCHAR(255) NOT NULL);

ALTER TABLE BOOK
    ADD FOREIGN KEY (JENRE_ID)
    REFERENCES JENRE(ID);

ALTER TABLE BOOK
    ADD FOREIGN KEY (AUTHOR_ID)
    REFERENCES AUTHOR(ID);

ALTER TABLE JENRE
    ADD CONSTRAINT JENRE_NAME_UNIQUE
    UNIQUE (NAME);



